name: MinigamesLibBungee
main: com.instancedev.minigamesapibungee.Main
version: 2.0.0
author: InstanceLabs
commands:
   mg:
      description: Main command
      usage: /mg [action]
      aliases: [mglib, mgapi, mapi, mglibbungee, join]
